# Generated by Django 2.2.5 on 2019-09-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNum', models.IntegerField()),
                ('name', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('std', models.IntegerField()),
                ('div', models.TextField()),
                ('religion', models.TextField()),
                ('cast', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
    ]
