# Generated by Django 2.2.7 on 2019-11-16 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std', models.CharField(max_length=10)),
                ('fees', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNum', models.IntegerField()),
                ('first_name', models.CharField(default='first name', max_length=101)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(default='last name', max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('address', models.TextField()),
                ('std', models.CharField(choices=[('LKG', 'LKG'), ('UKG', 'UKG')], default='LKG', max_length=10)),
                ('div', models.TextField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A')),
                ('religion', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('category', models.TextField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('NT', 'NT')], default='General')),
                ('fees', models.FloatField(blank=True, null=True)),
                ('dob', models.DateField(default=datetime.date(2019, 11, 16))),
                ('joining_date', models.DateField(blank=True, default=datetime.date(2019, 11, 16))),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(default='birth place', max_length=100)),
                ('prev_school', models.TextField(blank=True, null=True)),
                ('student_id', models.IntegerField(default=0)),
                ('aadhar_no', models.CharField(blank=True, max_length=20)),
                ('register_no', models.CharField(default='reg no', max_length=50)),
                ('total_fee_received', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('rollNum', 'div', 'std')},
            },
        ),
    ]
